<?php
define("DBHOST","localhost");
define("DBPORT","5432");
define("DBNAME","ptaw-2024-gr2");
define("DBUSER","ptaw-2024-gr2");
define("DBPASS","Hrw4zTS$[i\D_\$vI");
/*
define("DBHOST","localhost");
define("DBPORT","5432");
define("DBNAME","ptaw");
define("DBUSER","postgres");
define("DBPASS","test"); 

/define("DBHOST","localhost");
define("DBPORT","5432");
define("DBNAME","ptaw_fooddash");
define("DBUSER","postgres");
define("DBPASS","2023#Univ");
 */